version: "3.8"

services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: trpc
      POSTGRES_PASSWORD: trpc
      POSTGRES_DB: trpc
    restart: always
    networks:
      - lesson

networks:
  lesson: #
